language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t yrroth/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true yrroth/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: nginx-app
  env: nginxapp-env
  bucket_name: elasticbeanstalk-us-east-2-542961975769
  bucket_path: nginx-app
  'on':
    branch: master
  #Testing Permissions
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

