language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t yrroth/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yrroth/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: " "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-542961975769"
  bucket_path: "docker-react" 
  on:
    brach: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY